# This is a basic workflow to help you get started with Actions

name: Build and Test

# Controls when the workflow will run
on: 
  # push:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    # The type of runner that the job will run on
    strategy:
      matrix:
        python-minor-version: ["9", "10", "11", "12"]
      fail-fast: true
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.${{ matrix.python-minor-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.${{ matrix.python-minor-version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: 'cp3${{ matrix.python-minor-version }}-*'
          # rust doesn't seem to be available for musl linux on i686
          CIBW_SKIP: '*-musllinux_i686 *_ppc64le *_s390x'
        #   # we build for "alt_arch_name" if it exists, else 'auto'
          CIBW_ARCHS: 'all'
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH" CARGO_TERM_COLOR="always"'
        #   CIBW_ENVIRONMENT_WINDOWS: 'PATH="$UserProfile\.cargo\bin;$PATH"'
        #   CIBW_BEFORE_BUILD: rustup show
          CIBW_BEFORE_BUILD_LINUX: >
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=minimal -y &&
            rustup show
        #   CIBW_TEST_SKIP: '*-macosx_arm64 *-macosx_universal2:arm64'
        #   CIBW_BUILD_VERBOSITY: 1
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-3.${{ matrix.python-minor-version }}
          compression-level: 0
          path: wheelhouse/*.whl
  build-mac:
    # The type of runner that the job will run on
    strategy:
      matrix:
        python-minor-version: ["9", "10", "11", "12"]
      fail-fast: true
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.${{ matrix.python-minor-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.${{ matrix.python-minor-version }}
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: 'cp3${{ matrix.python-minor-version }}-*'
          CIBW_ARCHS: 'x86_64'
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH" CARGO_TERM_COLOR="always"'
          CIBW_BEFORE_BUILD_LINUX: >
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=minimal -y &&
            rustup show
        #   CIBW_TEST_SKIP: '*-macosx_arm64 *-macosx_universal2:arm64'
        #   CIBW_BUILD_VERBOSITY: 1
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-mac-3.${{ matrix.python-minor-version }}
          compression-level: 0
          path: wheelhouse/*.whl
